In [317]:
import math
import numpy as np




def halfAdder(a, b):
    return bool(a) != bool(b), bool(a) and bool(b)


def sigmoid(x):
    return 1/(1+math.e**-x)

def logit(x):
    return np.log(np.divide(x, np.subtract(1, x)))




class NeuralNetwork:
    def __init__(self, numInput, numHidden, numOutput, step):
        self.step = step
        self.hidden = np.matrix(np.random.rand(numHidden, numInput))
        self.outputs = np.matrix(np.random.rand(numOutput, numHidden))
    
    
    
    def train(self, data):
        for d in data:
            hiddenOut, output = self.forward(d[0])
            self.backward(hiddenOut, output, d[1])
    
    
    
    # feed forward data from in to out
    def forward(self, inputs):
        # feed forward from input to hidden
        hiddenOut = np.dot(self.hidden, inputs)
        
        # feed forward from hidden to output
        output = np.dot(self.outputs, hiddenOut)
        
        return hiddenOut, output
    
    
    
    # calculate delta and backpropagate the errors
    def backward(self, hiddenOut, outputs, outputExpected):
        # calculate output deltas (errors)
        outputDeltas = np.subtract(outputExpected, outputs)
        print(outputDeltas)
        # set output node weights
        # multiply output weights with step
        curWeights = np.dot(self.step, self.outputs)
        allWeights = []
        
        # split the weights and multiply each with the corresponding delta
        for i, w in enumerate(curWeights):
            allWeights.append(np.dot(outputDeltas[i], w).tolist()[0])
        # combined them back together into a matrix
        self.outputs = np.matrix(allWeights)
        
        '''
        # calculate hidden layer deltas by backpropagating through weights
        # repeat the outputs so its easily multiplied by weights
        organizedOutputs = np.repeat(np.matrix(logit(outputs)), len(self.outputs), axis=1).T
        ###########################################  ^---- can't be outputExpected either, something else...
        
        # get average of the target x weight
        hiddenExpected = np.divide(np.diag(np.dot(organizedOutputs, self.outputs)), len(self.outputs))
        hiddenDeltas = np.subtract(hiddenExpected, hiddenOut)
        
        # set hidden layer node weights
        # multiply hidden layer weights with step
        curWeights = np.dot(self.step, self.hidden)
        allWeights = []
        
        # split the weights and multiply each with the corresponding delta
        for i, w in enumerate(curWeights):
            allWeights.append(np.dot(hiddenDeltas[i], w).tolist()[0])
        # combined them back together into a matrix
        self.hidden = np.matrix(allWeights)'''

In [321]:
nn = NeuralNetwork(2, 3, 2, 0.1)

trainData = []
for _ in range(10):
    a = np.random.randint(2)
    b = np.random.randint(2)
    trainData.append([[[a], [b]], [[int(halfAdder(a, b)[0])], [int(halfAdder(a, b)[1])]]])
nn.train(trainData)

[[ 0.25123144]
 [-1.56470593]]
[[-0.03604913]
 [ 1.47054062]]
[[ 0.]
 [ 0.]]
[[ 0.]
 [ 0.]]
[[ 1.]
 [ 0.]]
[[ 0.]
 [ 0.]]
[[ 0.]
 [ 1.]]
[[ 0.]
 [ 1.]]
[[ 1.]
 [ 0.]]
[[ 1.]
 [ 0.]]
